/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.api;

import com.cisco.px.client.ApiException;
import com.cisco.px.client.model.ErrorResponse;
import com.cisco.px.client.model.SuccessTracksResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CxMetaDataApi
 */
@Disabled
public class CxMetaDataApiTest {

    private final CxMetaDataApi api = new CxMetaDataApi();

    /**
     * List success tracks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSuccessTracksTest() throws ApiException {
        SuccessTracksResponse response = api.getSuccessTracks();
        // TODO: test validations
    }

}
