/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccSessionAttendees
 */
public class AccSessionAttendeesTest {
    private final AccSessionAttendees model = new AccSessionAttendees();

    /**
     * Model tests for AccSessionAttendees
     */
    @Test
    public void testAccSessionAttendees() {
        // TODO: test AccSessionAttendees
    }

    /**
     * Test the property 'attendeeEmail'
     */
    @Test
    public void attendeeEmailTest() {
        // TODO: test attendeeEmail
    }

    /**
     * Test the property 'attendeeName'
     */
    @Test
    public void attendeeNameTest() {
        // TODO: test attendeeName
    }

}
