/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssetsViolations
 */
public class AssetsViolationsTest {
    private final AssetsViolations model = new AssetsViolations();

    /**
     * Model tests for AssetsViolations
     */
    @Test
    public void testAssetsViolations() {
        // TODO: test AssetsViolations
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'assetName'
     */
    @Test
    public void assetNameTest() {
        // TODO: test assetName
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'softwareType'
     */
    @Test
    public void softwareTypeTest() {
        // TODO: test softwareType
    }

    /**
     * Test the property 'softwareRelease'
     */
    @Test
    public void softwareReleaseTest() {
        // TODO: test softwareRelease
    }

    /**
     * Test the property 'productFamily'
     */
    @Test
    public void productFamilyTest() {
        // TODO: test productFamily
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'severity'
     */
    @Test
    public void severityTest() {
        // TODO: test severity
    }

    /**
     * Test the property 'lastChecked'
     */
    @Test
    public void lastCheckedTest() {
        // TODO: test lastChecked
    }

    /**
     * Test the property 'scanStatus'
     */
    @Test
    public void scanStatusTest() {
        // TODO: test scanStatus
    }

    /**
     * Test the property 'violationCount'
     */
    @Test
    public void violationCountTest() {
        // TODO: test violationCount
    }

    /**
     * Test the property 'mgmtSystemHostname'
     */
    @Test
    public void mgmtSystemHostnameTest() {
        // TODO: test mgmtSystemHostname
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'mgmtSystemType'
     */
    @Test
    public void mgmtSystemTypeTest() {
        // TODO: test mgmtSystemType
    }

}
