/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.cisco.px.client.model.CustomerDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContractV2
 */
public class ContractV2Test {
    private final ContractV2 model = new ContractV2();

    /**
     * Model tests for ContractV2
     */
    @Test
    public void testContractV2() {
        // TODO: test ContractV2
    }

    /**
     * Test the property 'contractNumber'
     */
    @Test
    public void contractNumberTest() {
        // TODO: test contractNumber
    }

    /**
     * Test the property 'contractStatus'
     */
    @Test
    public void contractStatusTest() {
        // TODO: test contractStatus
    }

    /**
     * Test the property 'contractValue'
     */
    @Test
    public void contractValueTest() {
        // TODO: test contractValue
    }

    /**
     * Test the property 'coverageStartDate'
     */
    @Test
    public void coverageStartDateTest() {
        // TODO: test coverageStartDate
    }

    /**
     * Test the property 'coverageEndDate'
     */
    @Test
    public void coverageEndDateTest() {
        // TODO: test coverageEndDate
    }

    /**
     * Test the property 'customerDetails'
     */
    @Test
    public void customerDetailsTest() {
        // TODO: test customerDetails
    }

    /**
     * Test the property 'serviceLevel'
     */
    @Test
    public void serviceLevelTest() {
        // TODO: test serviceLevel
    }

    /**
     * Test the property 'successTrackIds'
     */
    @Test
    public void successTrackIdsTest() {
        // TODO: test successTrackIds
    }

    /**
     * Test the property 'onboardedStatus'
     */
    @Test
    public void onboardedStatusTest() {
        // TODO: test onboardedStatus
    }

}
