/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeviceDetail
 */
public class DeviceDetailTest {
    private final DeviceDetail model = new DeviceDetail();

    /**
     * Model tests for DeviceDetail
     */
    @Test
    public void testDeviceDetail() {
        // TODO: test DeviceDetail
    }

    /**
     * Test the property 'crashCount'
     */
    @Test
    public void crashCountTest() {
        // TODO: test crashCount
    }

    /**
     * Test the property 'firstCrashDate'
     */
    @Test
    public void firstCrashDateTest() {
        // TODO: test firstCrashDate
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'lastCrashDate'
     */
    @Test
    public void lastCrashDateTest() {
        // TODO: test lastCrashDate
    }

    /**
     * Test the property 'assetId'
     */
    @Test
    public void assetIdTest() {
        // TODO: test assetId
    }

    /**
     * Test the property 'assetUniqueId'
     */
    @Test
    public void assetUniqueIdTest() {
        // TODO: test assetUniqueId
    }

    /**
     * Test the property 'assetName'
     */
    @Test
    public void assetNameTest() {
        // TODO: test assetName
    }

    /**
     * Test the property 'productFamily'
     */
    @Test
    public void productFamilyTest() {
        // TODO: test productFamily
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'softwareType'
     */
    @Test
    public void softwareTypeTest() {
        // TODO: test softwareType
    }

    /**
     * Test the property 'softwareRelease'
     */
    @Test
    public void softwareReleaseTest() {
        // TODO: test softwareRelease
    }

    /**
     * Test the property 'mgmtSystemAddr'
     */
    @Test
    public void mgmtSystemAddrTest() {
        // TODO: test mgmtSystemAddr
    }

    /**
     * Test the property 'mgmtSystemHost'
     */
    @Test
    public void mgmtSystemHostTest() {
        // TODO: test mgmtSystemHost
    }

    /**
     * Test the property 'mgmtSytemType'
     */
    @Test
    public void mgmtSytemTypeTest() {
        // TODO: test mgmtSytemType
    }

}
