/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Faults
 */
public class FaultsTest {
    private final Faults model = new Faults();

    /**
     * Model tests for Faults
     */
    @Test
    public void testFaults() {
        // TODO: test Faults
    }

    /**
     * Test the property 'severity'
     */
    @Test
    public void severityTest() {
        // TODO: test severity
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'lastOccurence'
     */
    @Test
    public void lastOccurenceTest() {
        // TODO: test lastOccurence
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'caseAutomation'
     */
    @Test
    public void caseAutomationTest() {
        // TODO: test caseAutomation
    }

    /**
     * Test the property 'faultId'
     */
    @Test
    public void faultIdTest() {
        // TODO: test faultId
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'openCases'
     */
    @Test
    public void openCasesTest() {
        // TODO: test openCases
    }

    /**
     * Test the property 'affectedAssets'
     */
    @Test
    public void affectedAssetsTest() {
        // TODO: test affectedAssets
    }

    /**
     * Test the property 'occurences'
     */
    @Test
    public void occurencesTest() {
        // TODO: test occurences
    }

    /**
     * Test the property 'ignoredAssets'
     */
    @Test
    public void ignoredAssetsTest() {
        // TODO: test ignoredAssets
    }

    /**
     * Test the property 'mgmtSystemType'
     */
    @Test
    public void mgmtSystemTypeTest() {
        // TODO: test mgmtSystemType
    }

    /**
     * Test the property 'mgmtSystemAddr'
     */
    @Test
    public void mgmtSystemAddrTest() {
        // TODO: test mgmtSystemAddr
    }

    /**
     * Test the property 'mgmtSystemHostname'
     */
    @Test
    public void mgmtSystemHostnameTest() {
        // TODO: test mgmtSystemHostname
    }

}
