/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.cisco.px.client.model.PartnerOfferAttendee;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PartnerOfferSession
 */
public class PartnerOfferSessionTest {
    private final PartnerOfferSession model = new PartnerOfferSession();

    /**
     * Model tests for PartnerOfferSession
     */
    @Test
    public void testPartnerOfferSession() {
        // TODO: test PartnerOfferSession
    }

    /**
     * Test the property 'attendeeList'
     */
    @Test
    public void attendeeListTest() {
        // TODO: test attendeeList
    }

    /**
     * Test the property 'businessOutcome'
     */
    @Test
    public void businessOutcomeTest() {
        // TODO: test businessOutcome
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'preferredSlot'
     */
    @Test
    public void preferredSlotTest() {
        // TODO: test preferredSlot
    }

    /**
     * Test the property 'reasonForInterest'
     */
    @Test
    public void reasonForInterestTest() {
        // TODO: test reasonForInterest
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

}
