/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.cisco.px.client.model.RacetrackUsecase;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RacetrackBuidSolution
 */
public class RacetrackBuidSolutionTest {
    private final RacetrackBuidSolution model = new RacetrackBuidSolution();

    /**
     * Model tests for RacetrackBuidSolution
     */
    @Test
    public void testRacetrackBuidSolution() {
        // TODO: test RacetrackBuidSolution
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'solutionId'
     */
    @Test
    public void solutionIdTest() {
        // TODO: test solutionId
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'cxLevel'
     */
    @Test
    public void cxLevelTest() {
        // TODO: test cxLevel
    }

    /**
     * Test the property 'usecases'
     */
    @Test
    public void usecasesTest() {
        // TODO: test usecases
    }

}
