/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SoftwareGroupRisk
 */
public class SoftwareGroupRiskTest {
    private final SoftwareGroupRisk model = new SoftwareGroupRisk();

    /**
     * Model tests for SoftwareGroupRisk
     */
    @Test
    public void testSoftwareGroupRisk() {
        // TODO: test SoftwareGroupRisk
    }

    /**
     * Test the property 'changeFromPrev'
     */
    @Test
    public void changeFromPrevTest() {
        // TODO: test changeFromPrev
    }

    /**
     * Test the property 'riskCategory'
     */
    @Test
    public void riskCategoryTest() {
        // TODO: test riskCategory
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'riskScore'
     */
    @Test
    public void riskScoreTest() {
        // TODO: test riskScore
    }

}
