/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SoftwareGroupSecurityAdvisories
 */
public class SoftwareGroupSecurityAdvisoriesTest {
    private final SoftwareGroupSecurityAdvisories model = new SoftwareGroupSecurityAdvisories();

    /**
     * Model tests for SoftwareGroupSecurityAdvisories
     */
    @Test
    public void testSoftwareGroupSecurityAdvisories() {
        // TODO: test SoftwareGroupSecurityAdvisories
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'advisoryVersion'
     */
    @Test
    public void advisoryVersionTest() {
        // TODO: test advisoryVersion
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'advisoryId'
     */
    @Test
    public void advisoryIdTest() {
        // TODO: test advisoryId
    }

    /**
     * Test the property 'impact'
     */
    @Test
    public void impactTest() {
        // TODO: test impact
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

}
