/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SoftwareGroup
 */
public class SoftwareGroupTest {
    private final SoftwareGroup model = new SoftwareGroup();

    /**
     * Model tests for SoftwareGroup
     */
    @Test
    public void testSoftwareGroup() {
        // TODO: test SoftwareGroup
    }

    /**
     * Test the property 'assetCount'
     */
    @Test
    public void assetCountTest() {
        // TODO: test assetCount
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'sourceSystemId'
     */
    @Test
    public void sourceSystemIdTest() {
        // TODO: test sourceSystemId
    }

    /**
     * Test the property 'selectedRelease'
     */
    @Test
    public void selectedReleaseTest() {
        // TODO: test selectedRelease
    }

    /**
     * Test the property 'productFamily'
     */
    @Test
    public void productFamilyTest() {
        // TODO: test productFamily
    }

    /**
     * Test the property 'softwareGroupName'
     */
    @Test
    public void softwareGroupNameTest() {
        // TODO: test softwareGroupName
    }

    /**
     * Test the property 'softwareGroupId'
     */
    @Test
    public void softwareGroupIdTest() {
        // TODO: test softwareGroupId
    }

    /**
     * Test the property 'suggestionId'
     */
    @Test
    public void suggestionIdTest() {
        // TODO: test suggestionId
    }

    /**
     * Test the property 'suggestions'
     */
    @Test
    public void suggestionsTest() {
        // TODO: test suggestions
    }

    /**
     * Test the property 'riskLevel'
     */
    @Test
    public void riskLevelTest() {
        // TODO: test riskLevel
    }

    /**
     * Test the property 'softwareType'
     */
    @Test
    public void softwareTypeTest() {
        // TODO: test softwareType
    }

    /**
     * Test the property 'currentReleases'
     */
    @Test
    public void currentReleasesTest() {
        // TODO: test currentReleases
    }

    /**
     * Test the property 'managedBy'
     */
    @Test
    public void managedByTest() {
        // TODO: test managedBy
    }

}
