/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SoftwareGroupFieldNotices
 */
public class SoftwareGroupFieldNoticesTest {
    private final SoftwareGroupFieldNotices model = new SoftwareGroupFieldNotices();

    /**
     * Model tests for SoftwareGroupFieldNotices
     */
    @Test
    public void testSoftwareGroupFieldNotices() {
        // TODO: test SoftwareGroupFieldNotices
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'fieldNoticeId'
     */
    @Test
    public void fieldNoticeIdTest() {
        // TODO: test fieldNoticeId
    }

    /**
     * Test the property 'firstPublished'
     */
    @Test
    public void firstPublishedTest() {
        // TODO: test firstPublished
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
