/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SolutionMapping
 */
public class SolutionMappingTest {
    private final SolutionMapping model = new SolutionMapping();

    /**
     * Model tests for SolutionMapping
     */
    @Test
    public void testSolutionMapping() {
        // TODO: test SolutionMapping
    }

    /**
     * Test the property 'pitstop'
     */
    @Test
    public void pitstopTest() {
        // TODO: test pitstop
    }

    /**
     * Test the property 'solution'
     */
    @Test
    public void solutionTest() {
        // TODO: test solution
    }

    /**
     * Test the property 'usecase'
     */
    @Test
    public void usecaseTest() {
        // TODO: test usecase
    }

}
