/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuccessTrackChecklistMapping
 */
public class SuccessTrackChecklistMappingTest {
    private final SuccessTrackChecklistMapping model = new SuccessTrackChecklistMapping();

    /**
     * Model tests for SuccessTrackChecklistMapping
     */
    @Test
    public void testSuccessTrackChecklistMapping() {
        // TODO: test SuccessTrackChecklistMapping
    }

    /**
     * Test the property 'checklist'
     */
    @Test
    public void checklistTest() {
        // TODO: test checklist
    }

    /**
     * Test the property 'checklistId'
     */
    @Test
    public void checklistIdTest() {
        // TODO: test checklistId
    }

    /**
     * Test the property 'mappingChecklistId'
     */
    @Test
    public void mappingChecklistIdTest() {
        // TODO: test mappingChecklistId
    }

}
