/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuggestionSummaryBugSeverityFixed
 */
public class SuggestionSummaryBugSeverityFixedTest {
    private final SuggestionSummaryBugSeverityFixed model = new SuggestionSummaryBugSeverityFixed();

    /**
     * Model tests for SuggestionSummaryBugSeverityFixed
     */
    @Test
    public void testSuggestionSummaryBugSeverityFixed() {
        // TODO: test SuggestionSummaryBugSeverityFixed
    }

    /**
     * Test the property 'high'
     */
    @Test
    public void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'low'
     */
    @Test
    public void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'medium'
     */
    @Test
    public void mediumTest() {
        // TODO: test medium
    }

}
