/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import com.cisco.px.client.model.SuggestionSummaryFieldNoticeSeverityExposed;
import com.cisco.px.client.model.SuggestionSummaryFieldNoticeSeverityFixed;
import com.cisco.px.client.model.SuggestionSummaryFieldNoticeSeverityNewExposed;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SuggestionSummaryFieldNoticeSeverity
 */
public class SuggestionSummaryFieldNoticeSeverityTest {
    private final SuggestionSummaryFieldNoticeSeverity model = new SuggestionSummaryFieldNoticeSeverity();

    /**
     * Model tests for SuggestionSummaryFieldNoticeSeverity
     */
    @Test
    public void testSuggestionSummaryFieldNoticeSeverity() {
        // TODO: test SuggestionSummaryFieldNoticeSeverity
    }

    /**
     * Test the property 'exposed'
     */
    @Test
    public void exposedTest() {
        // TODO: test exposed
    }

    /**
     * Test the property 'newExposed'
     */
    @Test
    public void newExposedTest() {
        // TODO: test newExposed
    }

    /**
     * Test the property 'fixed'
     */
    @Test
    public void fixedTest() {
        // TODO: test fixed
    }

}
