/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cisco.px.client.JSON;

/**
 * AffectedAssets
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-10T19:31:00.454334Z[Etc/UTC]", comments = "Generator version: 7.4.0")
public class AffectedAssets {
  public static final String SERIALIZED_NAME_ASSET_NAME = "assetName";
  @SerializedName(SERIALIZED_NAME_ASSET_NAME)
  private String assetName;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "productId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private String productId;

  public static final String SERIALIZED_NAME_CASE_NUMBER = "caseNumber";
  @SerializedName(SERIALIZED_NAME_CASE_NUMBER)
  private String caseNumber;

  public static final String SERIALIZED_NAME_CASE_ACTION = "caseAction";
  @SerializedName(SERIALIZED_NAME_CASE_ACTION)
  private String caseAction;

  public static final String SERIALIZED_NAME_OCCURRENCES = "occurrences";
  @SerializedName(SERIALIZED_NAME_OCCURRENCES)
  private Integer occurrences;

  public static final String SERIALIZED_NAME_FIRST_OCCURRENCE = "firstOccurrence";
  @SerializedName(SERIALIZED_NAME_FIRST_OCCURRENCE)
  private OffsetDateTime firstOccurrence;

  public static final String SERIALIZED_NAME_LAST_OCCURRENCE = "lastOccurrence";
  @SerializedName(SERIALIZED_NAME_LAST_OCCURRENCE)
  private OffsetDateTime lastOccurrence;

  public static final String SERIALIZED_NAME_FAULT_ID = "faultId";
  @SerializedName(SERIALIZED_NAME_FAULT_ID)
  private Integer faultId;

  public static final String SERIALIZED_NAME_SERIAL_NUMBER = "serialNumber";
  @SerializedName(SERIALIZED_NAME_SERIAL_NUMBER)
  private String serialNumber;

  public static final String SERIALIZED_NAME_MGMT_SYSTEM_TYPE = "mgmtSystemType";
  @SerializedName(SERIALIZED_NAME_MGMT_SYSTEM_TYPE)
  private String mgmtSystemType;

  public static final String SERIALIZED_NAME_MGMT_SYSTEM_ADDR = "mgmtSystemAddr";
  @SerializedName(SERIALIZED_NAME_MGMT_SYSTEM_ADDR)
  private String mgmtSystemAddr;

  public static final String SERIALIZED_NAME_MGMT_SYSTEM_HOSTNAME = "mgmtSystemHostname";
  @SerializedName(SERIALIZED_NAME_MGMT_SYSTEM_HOSTNAME)
  private String mgmtSystemHostname;

  public AffectedAssets() {
  }

  public AffectedAssets assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Unique asset name
   * @return assetName
  **/
  @javax.annotation.Nullable
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }


  public AffectedAssets productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Cisco product number of the asset
   * @return productId
  **/
  @javax.annotation.Nullable
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }


  public AffectedAssets caseNumber(String caseNumber) {
    this.caseNumber = caseNumber;
    return this;
  }

   /**
   * If case automation is enabled, this is the Cisco support case number created
   * @return caseNumber
  **/
  @javax.annotation.Nullable
  public String getCaseNumber() {
    return caseNumber;
  }

  public void setCaseNumber(String caseNumber) {
    this.caseNumber = caseNumber;
  }


  public AffectedAssets caseAction(String caseAction) {
    this.caseAction = caseAction;
    return this;
  }

   /**
   * If case automation is enabled, this is the status of the Cisco support case request submitted by CX Cloud for the asset
   * @return caseAction
  **/
  @javax.annotation.Nullable
  public String getCaseAction() {
    return caseAction;
  }

  public void setCaseAction(String caseAction) {
    this.caseAction = caseAction;
  }


  public AffectedAssets occurrences(Integer occurrences) {
    this.occurrences = occurrences;
    return this;
  }

   /**
   * Number of times the fault occurred on the asset
   * @return occurrences
  **/
  @javax.annotation.Nullable
  public Integer getOccurrences() {
    return occurrences;
  }

  public void setOccurrences(Integer occurrences) {
    this.occurrences = occurrences;
  }


  public AffectedAssets firstOccurrence(OffsetDateTime firstOccurrence) {
    this.firstOccurrence = firstOccurrence;
    return this;
  }

   /**
   * Date the fault first occurred on the asset
   * @return firstOccurrence
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getFirstOccurrence() {
    return firstOccurrence;
  }

  public void setFirstOccurrence(OffsetDateTime firstOccurrence) {
    this.firstOccurrence = firstOccurrence;
  }


  public AffectedAssets lastOccurrence(OffsetDateTime lastOccurrence) {
    this.lastOccurrence = lastOccurrence;
    return this;
  }

   /**
   * Date the fault last occurred on the asset
   * @return lastOccurrence
  **/
  @javax.annotation.Nullable
  public OffsetDateTime getLastOccurrence() {
    return lastOccurrence;
  }

  public void setLastOccurrence(OffsetDateTime lastOccurrence) {
    this.lastOccurrence = lastOccurrence;
  }


  public AffectedAssets faultId(Integer faultId) {
    this.faultId = faultId;
    return this;
  }

   /**
   * Unique identifier used in CX Cloud to identify the fault
   * @return faultId
  **/
  @javax.annotation.Nullable
  public Integer getFaultId() {
    return faultId;
  }

  public void setFaultId(Integer faultId) {
    this.faultId = faultId;
  }


  public AffectedAssets serialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Unique Cisco serial number of the asset
   * @return serialNumber
  **/
  @javax.annotation.Nullable
  public String getSerialNumber() {
    return serialNumber;
  }

  public void setSerialNumber(String serialNumber) {
    this.serialNumber = serialNumber;
  }


  public AffectedAssets mgmtSystemType(String mgmtSystemType) {
    this.mgmtSystemType = mgmtSystemType;
    return this;
  }

   /**
   * Get mgmtSystemType
   * @return mgmtSystemType
  **/
  @javax.annotation.Nullable
  public String getMgmtSystemType() {
    return mgmtSystemType;
  }

  public void setMgmtSystemType(String mgmtSystemType) {
    this.mgmtSystemType = mgmtSystemType;
  }


  public AffectedAssets mgmtSystemAddr(String mgmtSystemAddr) {
    this.mgmtSystemAddr = mgmtSystemAddr;
    return this;
  }

   /**
   * Get mgmtSystemAddr
   * @return mgmtSystemAddr
  **/
  @javax.annotation.Nullable
  public String getMgmtSystemAddr() {
    return mgmtSystemAddr;
  }

  public void setMgmtSystemAddr(String mgmtSystemAddr) {
    this.mgmtSystemAddr = mgmtSystemAddr;
  }


  public AffectedAssets mgmtSystemHostname(String mgmtSystemHostname) {
    this.mgmtSystemHostname = mgmtSystemHostname;
    return this;
  }

   /**
   * Get mgmtSystemHostname
   * @return mgmtSystemHostname
  **/
  @javax.annotation.Nullable
  public String getMgmtSystemHostname() {
    return mgmtSystemHostname;
  }

  public void setMgmtSystemHostname(String mgmtSystemHostname) {
    this.mgmtSystemHostname = mgmtSystemHostname;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AffectedAssets affectedAssets = (AffectedAssets) o;
    return Objects.equals(this.assetName, affectedAssets.assetName) &&
        Objects.equals(this.productId, affectedAssets.productId) &&
        Objects.equals(this.caseNumber, affectedAssets.caseNumber) &&
        Objects.equals(this.caseAction, affectedAssets.caseAction) &&
        Objects.equals(this.occurrences, affectedAssets.occurrences) &&
        Objects.equals(this.firstOccurrence, affectedAssets.firstOccurrence) &&
        Objects.equals(this.lastOccurrence, affectedAssets.lastOccurrence) &&
        Objects.equals(this.faultId, affectedAssets.faultId) &&
        Objects.equals(this.serialNumber, affectedAssets.serialNumber) &&
        Objects.equals(this.mgmtSystemType, affectedAssets.mgmtSystemType) &&
        Objects.equals(this.mgmtSystemAddr, affectedAssets.mgmtSystemAddr) &&
        Objects.equals(this.mgmtSystemHostname, affectedAssets.mgmtSystemHostname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetName, productId, caseNumber, caseAction, occurrences, firstOccurrence, lastOccurrence, faultId, serialNumber, mgmtSystemType, mgmtSystemAddr, mgmtSystemHostname);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AffectedAssets {\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    caseNumber: ").append(toIndentedString(caseNumber)).append("\n");
    sb.append("    caseAction: ").append(toIndentedString(caseAction)).append("\n");
    sb.append("    occurrences: ").append(toIndentedString(occurrences)).append("\n");
    sb.append("    firstOccurrence: ").append(toIndentedString(firstOccurrence)).append("\n");
    sb.append("    lastOccurrence: ").append(toIndentedString(lastOccurrence)).append("\n");
    sb.append("    faultId: ").append(toIndentedString(faultId)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    mgmtSystemType: ").append(toIndentedString(mgmtSystemType)).append("\n");
    sb.append("    mgmtSystemAddr: ").append(toIndentedString(mgmtSystemAddr)).append("\n");
    sb.append("    mgmtSystemHostname: ").append(toIndentedString(mgmtSystemHostname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("assetName");
    openapiFields.add("productId");
    openapiFields.add("caseNumber");
    openapiFields.add("caseAction");
    openapiFields.add("occurrences");
    openapiFields.add("firstOccurrence");
    openapiFields.add("lastOccurrence");
    openapiFields.add("faultId");
    openapiFields.add("serialNumber");
    openapiFields.add("mgmtSystemType");
    openapiFields.add("mgmtSystemAddr");
    openapiFields.add("mgmtSystemHostname");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AffectedAssets
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AffectedAssets.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AffectedAssets is not found in the empty JSON string", AffectedAssets.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AffectedAssets.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AffectedAssets` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("assetName") != null && !jsonObj.get("assetName").isJsonNull()) && !jsonObj.get("assetName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `assetName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assetName").toString()));
      }
      if ((jsonObj.get("productId") != null && !jsonObj.get("productId").isJsonNull()) && !jsonObj.get("productId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productId").toString()));
      }
      if ((jsonObj.get("caseNumber") != null && !jsonObj.get("caseNumber").isJsonNull()) && !jsonObj.get("caseNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caseNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseNumber").toString()));
      }
      if ((jsonObj.get("caseAction") != null && !jsonObj.get("caseAction").isJsonNull()) && !jsonObj.get("caseAction").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caseAction` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseAction").toString()));
      }
      if ((jsonObj.get("serialNumber") != null && !jsonObj.get("serialNumber").isJsonNull()) && !jsonObj.get("serialNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serialNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serialNumber").toString()));
      }
      if ((jsonObj.get("mgmtSystemType") != null && !jsonObj.get("mgmtSystemType").isJsonNull()) && !jsonObj.get("mgmtSystemType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mgmtSystemType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mgmtSystemType").toString()));
      }
      if ((jsonObj.get("mgmtSystemAddr") != null && !jsonObj.get("mgmtSystemAddr").isJsonNull()) && !jsonObj.get("mgmtSystemAddr").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mgmtSystemAddr` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mgmtSystemAddr").toString()));
      }
      if ((jsonObj.get("mgmtSystemHostname") != null && !jsonObj.get("mgmtSystemHostname").isJsonNull()) && !jsonObj.get("mgmtSystemHostname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mgmtSystemHostname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mgmtSystemHostname").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AffectedAssets.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AffectedAssets' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AffectedAssets> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AffectedAssets.class));

       return (TypeAdapter<T>) new TypeAdapter<AffectedAssets>() {
           @Override
           public void write(JsonWriter out, AffectedAssets value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AffectedAssets read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AffectedAssets given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AffectedAssets
  * @throws IOException if the JSON string is invalid with respect to AffectedAssets
  */
  public static AffectedAssets fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AffectedAssets.class);
  }

 /**
  * Convert an instance of AffectedAssets to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

