/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cisco.px.client.JSON;

/**
 * SoftwareGroupRisk
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-10T19:31:00.454334Z[Etc/UTC]", comments = "Generator version: 7.4.0")
public class SoftwareGroupRisk {
  public static final String SERIALIZED_NAME_CHANGE_FROM_PREV = "changeFromPrev";
  @SerializedName(SERIALIZED_NAME_CHANGE_FROM_PREV)
  private Double changeFromPrev;

  public static final String SERIALIZED_NAME_RISK_CATEGORY = "riskCategory";
  @SerializedName(SERIALIZED_NAME_RISK_CATEGORY)
  private String riskCategory;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private LocalDate date;

  public static final String SERIALIZED_NAME_RISK_SCORE = "riskScore";
  @SerializedName(SERIALIZED_NAME_RISK_SCORE)
  private Double riskScore;

  public SoftwareGroupRisk() {
  }

  public SoftwareGroupRisk changeFromPrev(Double changeFromPrev) {
    this.changeFromPrev = changeFromPrev;
    return this;
  }

   /**
   * The percentage the risk score has changed from the previous week
   * @return changeFromPrev
  **/
  @javax.annotation.Nullable
  public Double getChangeFromPrev() {
    return changeFromPrev;
  }

  public void setChangeFromPrev(Double changeFromPrev) {
    this.changeFromPrev = changeFromPrev;
  }


  public SoftwareGroupRisk riskCategory(String riskCategory) {
    this.riskCategory = riskCategory;
    return this;
  }

   /**
   * Risk level of the Cisco software release based on its risk score. The risk level can be High, Medium, or Low.
   * @return riskCategory
  **/
  @javax.annotation.Nullable
  public String getRiskCategory() {
    return riskCategory;
  }

  public void setRiskCategory(String riskCategory) {
    this.riskCategory = riskCategory;
  }


  public SoftwareGroupRisk date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Date the weekly risk score was calculated
   * @return date
  **/
  @javax.annotation.Nullable
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }


  public SoftwareGroupRisk riskScore(Double riskScore) {
    this.riskScore = riskScore;
    return this;
  }

   /**
   * Risk score of the Cisco software release for the softwareGroupRiskTrend date
   * @return riskScore
  **/
  @javax.annotation.Nullable
  public Double getRiskScore() {
    return riskScore;
  }

  public void setRiskScore(Double riskScore) {
    this.riskScore = riskScore;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SoftwareGroupRisk softwareGroupRisk = (SoftwareGroupRisk) o;
    return Objects.equals(this.changeFromPrev, softwareGroupRisk.changeFromPrev) &&
        Objects.equals(this.riskCategory, softwareGroupRisk.riskCategory) &&
        Objects.equals(this.date, softwareGroupRisk.date) &&
        Objects.equals(this.riskScore, softwareGroupRisk.riskScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeFromPrev, riskCategory, date, riskScore);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SoftwareGroupRisk {\n");
    sb.append("    changeFromPrev: ").append(toIndentedString(changeFromPrev)).append("\n");
    sb.append("    riskCategory: ").append(toIndentedString(riskCategory)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    riskScore: ").append(toIndentedString(riskScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("changeFromPrev");
    openapiFields.add("riskCategory");
    openapiFields.add("date");
    openapiFields.add("riskScore");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SoftwareGroupRisk
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SoftwareGroupRisk.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SoftwareGroupRisk is not found in the empty JSON string", SoftwareGroupRisk.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SoftwareGroupRisk.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SoftwareGroupRisk` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("riskCategory") != null && !jsonObj.get("riskCategory").isJsonNull()) && !jsonObj.get("riskCategory").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `riskCategory` to be a primitive type in the JSON string but got `%s`", jsonObj.get("riskCategory").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SoftwareGroupRisk.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SoftwareGroupRisk' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SoftwareGroupRisk> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SoftwareGroupRisk.class));

       return (TypeAdapter<T>) new TypeAdapter<SoftwareGroupRisk>() {
           @Override
           public void write(JsonWriter out, SoftwareGroupRisk value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SoftwareGroupRisk read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SoftwareGroupRisk given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SoftwareGroupRisk
  * @throws IOException if the JSON string is invalid with respect to SoftwareGroupRisk
  */
  public static SoftwareGroupRisk fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SoftwareGroupRisk.class);
  }

 /**
  * Convert an instance of SoftwareGroupRisk to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

