/*
 * PX Cloud for Success Tracks API
 * PX Cloud for Success Tracks API
 *
 * The version of the OpenAPI document: 0.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.cisco.px.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.cisco.px.client.JSON;

/**
 * Number of security advisories the current Cisco software releases are exposed to that are addressed by the suggested release, grouped by impact
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-05-10T19:31:00.454334Z[Etc/UTC]", comments = "Generator version: 7.4.0")
public class SuggestionSummaryAdvisoriesSeverityExposed {
  public static final String SERIALIZED_NAME_HIGH = "High";
  @SerializedName(SERIALIZED_NAME_HIGH)
  private Long high;

  public static final String SERIALIZED_NAME_LOW = "Low";
  @SerializedName(SERIALIZED_NAME_LOW)
  private Long low;

  public static final String SERIALIZED_NAME_MEDIUM = "Medium";
  @SerializedName(SERIALIZED_NAME_MEDIUM)
  private Long medium;

  public SuggestionSummaryAdvisoriesSeverityExposed() {
  }

  public SuggestionSummaryAdvisoriesSeverityExposed high(Long high) {
    this.high = high;
    return this;
  }

   /**
   * Number of High impact security advisories addressed by the suggested Cisco software release
   * @return high
  **/
  @javax.annotation.Nullable
  public Long getHigh() {
    return high;
  }

  public void setHigh(Long high) {
    this.high = high;
  }


  public SuggestionSummaryAdvisoriesSeverityExposed low(Long low) {
    this.low = low;
    return this;
  }

   /**
   * Number of Low impact security advisories addressed by the suggested Cisco software release
   * @return low
  **/
  @javax.annotation.Nullable
  public Long getLow() {
    return low;
  }

  public void setLow(Long low) {
    this.low = low;
  }


  public SuggestionSummaryAdvisoriesSeverityExposed medium(Long medium) {
    this.medium = medium;
    return this;
  }

   /**
   * Number of Medium impact security advisories addressed by the suggested Cisco software release
   * @return medium
  **/
  @javax.annotation.Nullable
  public Long getMedium() {
    return medium;
  }

  public void setMedium(Long medium) {
    this.medium = medium;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuggestionSummaryAdvisoriesSeverityExposed suggestionSummaryAdvisoriesSeverityExposed = (SuggestionSummaryAdvisoriesSeverityExposed) o;
    return Objects.equals(this.high, suggestionSummaryAdvisoriesSeverityExposed.high) &&
        Objects.equals(this.low, suggestionSummaryAdvisoriesSeverityExposed.low) &&
        Objects.equals(this.medium, suggestionSummaryAdvisoriesSeverityExposed.medium);
  }

  @Override
  public int hashCode() {
    return Objects.hash(high, low, medium);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuggestionSummaryAdvisoriesSeverityExposed {\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("High");
    openapiFields.add("Low");
    openapiFields.add("Medium");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to SuggestionSummaryAdvisoriesSeverityExposed
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SuggestionSummaryAdvisoriesSeverityExposed.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SuggestionSummaryAdvisoriesSeverityExposed is not found in the empty JSON string", SuggestionSummaryAdvisoriesSeverityExposed.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SuggestionSummaryAdvisoriesSeverityExposed.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SuggestionSummaryAdvisoriesSeverityExposed` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SuggestionSummaryAdvisoriesSeverityExposed.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SuggestionSummaryAdvisoriesSeverityExposed' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SuggestionSummaryAdvisoriesSeverityExposed> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SuggestionSummaryAdvisoriesSeverityExposed.class));

       return (TypeAdapter<T>) new TypeAdapter<SuggestionSummaryAdvisoriesSeverityExposed>() {
           @Override
           public void write(JsonWriter out, SuggestionSummaryAdvisoriesSeverityExposed value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SuggestionSummaryAdvisoriesSeverityExposed read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SuggestionSummaryAdvisoriesSeverityExposed given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SuggestionSummaryAdvisoriesSeverityExposed
  * @throws IOException if the JSON string is invalid with respect to SuggestionSummaryAdvisoriesSeverityExposed
  */
  public static SuggestionSummaryAdvisoriesSeverityExposed fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SuggestionSummaryAdvisoriesSeverityExposed.class);
  }

 /**
  * Convert an instance of SuggestionSummaryAdvisoriesSeverityExposed to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

